### ISSUE TITLE
Este logo creo que viene al hacer create-react-app, mejor cárgatelo

### ISSUE THREAD

**Issue by vicenlu** [Spanioulis/Sprint-6#1]
Si fuese una imagen válida, habría que ponerla en el directorio assets

https://github.com/Spanioulis/Sprint-6/blob/340630dde102f54f0160788bda576845325427d8/src/logo.svg?short_path=9dfc1c0#L1

**Comment by Spanioulis** [comment]
Ok Luis, eliminado archivo y commit creado (push a origin incluido).

Gracias!
